CREATE TABLE PUBLIC.USERS (
        USER_ID BIGINT NOT NULL AUTO_INCREMENT,
        USER_NAME CHARACTER VARYING(255),
        CONSTRAINT CONSTRAINT_4 PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.USERS (USER_ID);

CREATE TABLE PUBLIC.FRIENDSHIP (
       ID UUID NOT NULL,
       CREATED_TIME TIMESTAMP,
       UPDATED_TIME TIMESTAMP,
       STATUS ENUM('ACCEPTED', 'BLOCKED', 'REJECTED', 'REQUESTED'),
       RECEIVER_ID BIGINT,
       REQUESTER_ID BIGINT,
       CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID),
       CONSTRAINT UK8PNM9ROVGLQFDDXO47D2AFM35 UNIQUE (RECEIVER_ID,REQUESTER_ID),
       CONSTRAINT FK5KUAXBWSCAP950H164T23SGBY FOREIGN KEY (RECEIVER_ID) REFERENCES PUBLIC.USERS(USER_ID),
       CONSTRAINT FK608BQP7HF9DCQ8OW16PNDXXRF FOREIGN KEY (REQUESTER_ID) REFERENCES PUBLIC.USERS(USER_ID)
);
CREATE INDEX FK5KUAXBWSCAP950H164T23SGBY_INDEX_B ON PUBLIC.FRIENDSHIP (RECEIVER_ID);
CREATE INDEX FK608BQP7HF9DCQ8OW16PNDXXRF_INDEX_B ON PUBLIC.FRIENDSHIP (REQUESTER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_B ON PUBLIC.FRIENDSHIP (ID);
CREATE UNIQUE INDEX UK8PNM9ROVGLQFDDXO47D2AFM35_INDEX_B ON PUBLIC.FRIENDSHIP (REQUESTER_ID,RECEIVER_ID);